# Generated by Django 4.1 on 2022-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=150, verbose_name="Apellido")),
                (
                    "correo",
                    models.EmailField(
                        max_length=150, verbose_name="Correo Electrónico"
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
            },
        ),
        migrations.CreateModel(
            name="Subscriptor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=150, verbose_name="Correo Electrónico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriptor",
                "verbose_name_plural": "Subscriptores",
            },
        ),
    ]
