# Generated by Django 4.0.3 on 2022-08-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sidebar',
            field=models.TextField(null=True),
        ),
    ]
