# Generated by Django 4.1 on 2022-08-18 18:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_posts_sidebar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=120, verbose_name="Apellidos"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=150, verbose_name="Correo Electrónico"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("web", models.URLField(blank=True, null=True, verbose_name="Web")),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "github",
                    models.URLField(blank=True, null=True, verbose_name="GitHub"),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Categoria",
                    ),
                ),
                (
                    "imagen_referencial",
                    models.ImageField(
                        upload_to="categoria/images/", verbose_name="Imagen Referencial"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Titulo del Post"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=150, unique=True, verbose_name="Slug"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("contenido", ckeditor.fields.RichTextField()),
                (
                    "img",
                    models.ImageField(
                        max_length=255, upload_to="blog/images/", verbose_name="Imagen"
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(
                        default=False, verbose_name="Publicado/No Publicado"
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateField(verbose_name="Fecha publcación"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.autor"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.categoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="RedesSociales",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("instagram", models.URLField(verbose_name="Instagram")),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "stackoverflow",
                    models.URLField(
                        blank=True, null=True, verbose_name="Stackoverflow"
                    ),
                ),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
            },
        ),
        migrations.CreateModel(
            name="Web",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "fecha_eliminacion",
                    models.DateField(
                        auto_now=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("nosotros", models.TextField(verbose_name="Nosotros")),
                (
                    "email",
                    models.EmailField(
                        max_length=150, verbose_name="Correo Electrónico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Web",
                "verbose_name_plural": "Webs",
            },
        ),
        migrations.DeleteModel(
            name="Posts",
        ),
    ]
