# Generated by Django 4.1 on 2022-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_autor_categoria_post_redessociales_web_delete_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/autores/",
                verbose_name="Imagen Referencial",
            ),
        ),
    ]
